### PR TITLE
Small yet nice changes

### PR DESCRIPTION
**Pull request by 3kh0**
I wanted to help, so I just made a few minor changes, here is a list of them!

- Added capitalization.
- Made it so when you hover over `BlooketUI`, it has a special cursor.
- Updated the bottom text to something more simple.

And here is a preview of the panel,

Screenshot 2022-04-20 5 23 42 PM

### CODE REVIEW

**Comment by notzastix** [comment]
looks good

**Comment by smintf** [comment]
Sorry i've had to edit your commit and delete your screenshot, as you basically leaked your Blooket Username.

**Comment by notzastix** [comment]
> Sorry i've had to edit your commit and delete your screenshot, as you basically leaked your Blooket Username.

Why? I'm not sure if you can do anything with someone's Blooket Username.

**Comment by smintf** [comment]
There's always the risk of being banned when someone from the Blooket Team notices that blunder.

**Comment by notzastix** [comment]
Ah

**Comment by coolman3289** [comment]
Well his Blooket name is very very similar to his GitHub name, I think they would have figured it out.

**Comment by 3kh0** [comment]
yeah true, thanks for the save @smintf!

**Pull request merged**
