### PR TITLE
Update bug.yml

### PR DESCRIPTION
**Pull request by coolman3289**
Capitalization fix.

### CODE REVIEW

**Comment by 3kh0** [comment]
Not needed, there is no reason.

**Comment by notzastix** [comment]
looks like someone wants contributor

**Comment by coolman3289** [comment]
Do it yourself instead of merging, I did this because names have to be capitalized. It is correct.

**Comment by vantr-o** [comment]
> Do it yourself instead of merging, I did this because names have to be capitalized. It is correct.

It may be correct but no need for a PR.

**Pull request closed without merging**
